# Generated by Django 3.0.8 on 2020-07-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
        migrations.AlterField(
            model_name='auction',
            name='Highest_Bidder',
            field=models.CharField(default='wow', max_length=64),
        ),
    ]
