# Generated by Django 3.0.8 on 2020-07-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200722_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='page',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
