# Generated by Django 3.0.8 on 2020-07-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=30)),
                ('likes', models.IntegerField()),
                ('time', models.CharField(max_length=30)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
